services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80" # HTTP port
    volumes:
      - /Users/vinaykumar/Projects/MOJ/GITHUB/samvad-deployment/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api1
      - api2

  api1:
    build: ./api1
    environment:
      MONGODB_ATLAS_URI: "mongodb+srv://Cluster79836:aWxgYHNCelhE@cluster79836.0uqw1.mongodb.net/"
      MONGODB_DATABASE_NAME: "samvad"
      MONGODB_COLLECTION_NAME: "study_materials"

  api2:
    build: ./api2
    environment:
      MONGODB_ATLAS_URI: "mongodb+srv://Cluster79836:aWxgYHNCelhE@cluster79836.0uqw1.mongodb.net/"
      MONGODB_DATABASE_NAME: "samvad"
      MONGODB_COLLECTION_NAME: "study_materials"


